version: '3'

services:
  database:
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.7      
  
  app-create:
    build:
      context: ./web-app-create/
      dockerfile: Dockerfile
    image: app/create-user:development
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:     
      - database
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    # env_file: .env
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
    links:
    - database:db
    depends_on:
    - database
    - redis

  app-list:
    build:
          context: ./web-app-list/
          dockerfile: Dockerfile
    image: app/list-users:development
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:     
      - database
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    # env_file: .env
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
    links:
    - database:db
    depends_on:
    - database
    - redis

volumes:
  gem_cache:
  db_data:
  node_modules: 
  db: 


