version: '3'
services:
  redis:
    image: redis
  db:
    image: postgres
    ports:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: bundle exec rerun -- rackup -p 3000 -o 0.0.0.0
    volumes:
      - .:/app
      - ./bundle-path:/bundle
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
    environment:
       REDIS_URL: redis://redis:6379/12
       BUNDLE_PATH: /bundle/vendor
       EDITOR: vi #for credentials editing
       WEBPACKER_DEV_SERVER_HOST: webpacker
  sidekiq:
    build: .
    command: bundle exec sidekiq
    environment:
      REDIS_URL: redis://redis:6379/12
      BUNDLE_PATH: /bundle/vendor
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - ./bundle-path:/bundle
  webpacker:
    build: .
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
    ports:
      - '3035:3035'

volumes:
  bundle-path:
  postgres-data: