version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: development
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql

  app-create:
    build:
      context: ./web-app-create
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app_create
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql2://admin:admin@db/development

  app-list:
    build:
      context: ./web-app-list
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - .:/app_list
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql2://admin:admin@db/development

volumes:
  db_data:
  app_create:
  app_list: