default: &default
  adapter: mysql2
  username: admin
  password: admin
  host: db
  port: 3306
  encoding: utf8mb4

development:
  <<: *default
  database: banco_development

test:
  <<: *default
  database: banco_test

production:
  <<: *default
  database: banco_production
